Uniform treatment of hoq* scripts

diff --git a/hoqc b/hoqc
--- a/hoqc
+++ b/hoqc
@@ -27,21 +27,29 @@ function readlink_f() {
 }
 
 mydir="$(dirname "$(readlink_f "$0")")"
+if [ ! -f "$mydir/hoq-config" ]
+then
+  echo "Could not find hoq-config. Did you run ./configure?"
+  exit 1
+fi
+
 . "$mydir/hoq-config"
 if [ "x$COQC" = "xno" ]
 then
   echo "Fatal error: coqc with -indices-matter was not found during configuration."
-else
-  # We could stick the arguments in hoq-config in COQ_ARGS, and then,
-  # using (non-portable) bash arrays, do
-  # $ exec "$COQC" "${COQ_ARGS[@]}" "$@"
-  # or using more evil (but portable) 'eval', do
-  # $ eval 'exec "$COQC" '"$COQ_ARGS"' "$@"'
-  # Instead, we duplicate code, because it's simpler.
-  if test "x$ssr" = "xyes"
-  then
-    exec "$COQC" -no-native-compiler -coqlib "$COQLIB" -R "$HOTTLIB" HoTT -R "$SSRLIB" Ssreflect -indices-matter "$@"
-  else
-    exec "$COQC" -no-native-compiler -coqlib "$COQLIB" -R "$HOTTLIB" HoTT -indices-matter "$@"
-  fi
+  exit 1
 fi
+
+# We could stick the arguments in hoq-config in COQ_ARGS, and then,
+# using (non-portable) bash arrays, do
+# $ exec "$COQC" "${COQ_ARGS[@]}" "$@"
+# or using more evil (but portable) 'eval', do
+# $ eval 'exec "$COQC" '"$COQ_ARGS"' "$@"'
+# Instead, we duplicate code, because it's simpler.
+if test "x$ssr" = "xyes"
+then
+  exec "$COQC" -no-native-compiler -coqlib "$COQLIB" -R "$HOTTLIB" HoTT -R "$SSRLIB" Ssreflect -indices-matter "$@"
+else
+  exec "$COQC" -no-native-compiler -coqlib "$COQLIB" -R "$HOTTLIB" HoTT -indices-matter "$@"
+fi
+
diff --git a/hoqdep b/hoqdep
--- a/hoqdep
+++ b/hoqdep
@@ -27,6 +27,20 @@ function readlink_f() {
 }
 
 mydir="$(dirname "$(readlink_f "$0")")"
+if [ ! -f "$mydir/hoq-config" ]
+then
+  echo "Could not find hoq-config. Did you run ./configure?"
+  exit 1
+fi
+
+. "$mydir/hoq-config"
+if [ "x$COQDEP" = "xno" ]
+then
+  echo "Fatal error: coqdep with -indices-matter was not found during configuration."
+  exit 1
+fi
+
+mydir="$(dirname "$(readlink_f "$0")")"
 . "$mydir/hoq-config"
 # We could stick the arguments in hoq-config in COQ_ARGS, and then,
 # using (non-portable) bash arrays, do
